# Site settings
Name: Jing Jin
Location: Hangzhou, China
Company: Center of Congitive and Brain Disorder, Hangzhou Normal Universtiy & The Affilated hosptial of Hangzhou Normal Universtiy
Position: 
Github: https://github.com/ikym
Facebook: https://www.facebook.com/
Phone: 132653351111
E-mail: nina1204@126.com

baseurl: "/nina1204.github.io"

permalink: /:year/:month/:day/:title/

exclude: ['README.md']

# Build settings
markdown: kramdown

