# Site settings
name: Jing Jin
location: Hangzhou, China
company: Unemployed
position: 网站编辑
github: https://github.com/ikym
facebook: https://www.facebook.com/
phone: 132653351111
email: nina1204@126.com

baseurl: "/nina1204.github.io"

permalink: /:year/:month/:day/:title/

exclude: ['README.md']

# Build settings
markdown: kramdown

